package com.chinavisamap.controller;

import com.chinavisamap.entity.CountryDetail;
import com.chinavisamap.entity.CountryPolicy;
import com.chinavisamap.service.CountryCodeResolver;
import com.chinavisamap.service.SeoService;
import com.chinavisamap.service.StructuredDataService;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.core.io.ClassPathResource;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriComponentsBuilder;
import java.net.URI;
import java.util.*;

@Controller
public class CountryController {
    private static final String NIA_SOURCE="https://en.nia.gov.cn/";
    private static final String VERIFIED_DATE="2026-09-05";
    private static final Set<String> CURRENT_UNILATERAL_30 = Collections.unmodifiableSet(new HashSet<String>() {{
        add("kyrgyzstan");
        add("vietnam");
    }});
    private final Map<String,CountryDetail> unilateralMap,mutualMap,transitMap;
    private final Map<String,Map<String,Object>> countryExtraMap;
    private final CountryCodeResolver resolver; private final SeoService seoService; private final StructuredDataService structuredDataService;
    public CountryController(ObjectMapper mapper,CountryCodeResolver resolver,SeoService seoService,StructuredDataService structuredDataService){this.resolver=resolver;this.seoService=seoService;this.structuredDataService=structuredDataService;unilateralMap=loadCountryMap(mapper,"unilateral.json");mutualMap=loadCountryMap(mapper,"mutual.json");transitMap=loadCountryMap(mapper,"transit.json");countryExtraMap=loadExtraMap(mapper);}
    @GetMapping(value="/country/{code}",params="type") public ResponseEntity<Void> legacyCountryRedirect(@PathVariable String code,@RequestParam String type,@RequestParam(defaultValue="en") String lang){if(getCountryDetail(code,type)==null)return ResponseEntity.notFound().build();String location=UriComponentsBuilder.fromPath("/country/"+routeCode(code)+"/"+type).queryParam("lang",seoService.normalizeLang(lang)).build().encode().toUriString();HttpHeaders h=new HttpHeaders();h.setLocation(URI.create(location));return new ResponseEntity<>(h,HttpStatus.MOVED_PERMANENTLY);}
    @GetMapping("/country/{code}") public String countryHome(@PathVariable String code,@RequestParam(defaultValue="en") String lang,Model model){String l=seoService.normalizeLang(lang);List<String>types=detectAvailableTypes(code);if(types.isEmpty())return "redirect:/?lang="+l;String pc=routeCode(code);CountryDetail d=getAnyCountryDetail(code);Map<String,Object>e=getCountryExtraRoot(code);String path="/country/"+pc;String c=seoService.canonical(path,l);model.addAttribute("code",pc);model.addAttribute("lang",l);model.addAttribute("detailCountry",d);model.addAttribute("availableTypes",types);model.addAttribute("countryExtraRoot",e);model.addAttribute("countryProfile",buildCountryProfile(pc,d,e));model.addAttribute("availablePolicies",buildAvailablePolicies(code,types));model.addAttribute("countryNames",buildCountryNames());model.addAttribute("relatedCountryCodes",buildRelatedCountryCodes(e));model.addAttribute("canonicalUrl",c);model.addAttribute("hreflang",seoService.hreflang(path));model.addAttribute("structuredData",structuredDataService.buildCountryHome(d,l,c,e,types,buildPolicyDetails(code,types)));return "country-home";}
    @GetMapping("/country/{code}/{type}") public String restCountryDetail(@PathVariable String code,@PathVariable String type,@RequestParam(defaultValue="en") String lang,Model model){String l=seoService.normalizeLang(lang);CountryDetail d=getCountryDetail(code,type);if(d==null)return "redirect:/?lang="+l;String pc=routeCode(code);String path="/country/"+pc+"/"+type;String c=seoService.canonical(path,l);Map<String,Object>e=asMap(getCountryExtraItem(code,type));Map<String,Object>root=getCountryExtraRoot(code);CountryPolicy p=buildCountryPolicy(pc,type,d,e);model.addAttribute("canonicalUrl",c);model.addAttribute("hreflang",seoService.hreflang(path));model.addAttribute("structuredData",structuredDataService.buildCountry(d,l,c,p,e));model.addAttribute("detail",d);model.addAttribute("policy",p);model.addAttribute("code",pc);model.addAttribute("type",type);model.addAttribute("lang",l);model.addAttribute("countryExtra",e);model.addAttribute("countryProfile",buildCountryProfile(pc,d,root));model.addAttribute("availableTypes",detectAvailableTypes(code));model.addAttribute("policyDetails",buildPolicyDetails(code,detectAvailableTypes(code)));return "country-detail";}
    private Map<String,Object> buildCountryProfile(String code,CountryDetail d,Map<String,Object>e){Map<String,Object>p=new LinkedHashMap<>();p.put("code",code);p.put("priority",e==null?999:number(e.get("priority"),999));p.put("tier",firstNonBlank(string(e,"tier"),"C"));p.put("heroQuestionEn",firstNonBlank(string(e,"homeHeroQuestionEn"),"Do "+d.getName()+" citizens need a visa for China?"));p.put("heroQuestionZh",firstNonBlank(string(e,"homeHeroQuestionZh"),d.getNameZh()+"公民去中国需要签证吗？"));p.put("heroAnswerEn",firstNonBlank(string(e,"homeHeroAnswerEn"),"Your visa requirement depends on your passport, purpose, stay and the China entry policy that applies to your itinerary."));p.put("heroAnswerZh",firstNonBlank(string(e,"homeHeroAnswerZh"),"是否需要签证取决于护照、出行目的、停留时间以及适用于你行程的中国入境政策。"));p.put("introEn",firstNonBlank(string(e,"homeIntroEn"),"Use the eligibility checker first, then open the policy that matches your trip."));p.put("introZh",firstNonBlank(string(e,"homeIntroZh"),"建议先使用资格检查器，再进入与你行程相匹配的政策详情页。"));return p;}
    private CountryPolicy buildCountryPolicy(String code,String type,CountryDetail d,Map<String,Object>e){CountryPolicy p=new CountryPolicy();p.setDetail(d);p.setCountryCode(code);p.setPolicyType(type);p.setOfficialSource(firstNonBlank(string(e,"officialSource"),NIA_SOURCE));p.setLastVerified(firstNonBlank(string(e,"lastVerified"),VERIFIED_DATE));p.setPolicyExpiry(string(e,"policyExpiry"));p.setPermittedPurposesEn(firstNonBlank(string(e,"permittedPurposesEn"),d.getPurpose()));p.setPermittedPurposesZh(firstNonBlank(string(e,"permittedPurposesZh"),d.getPurposeZh()));boolean t="transit".equals(type),m="mutual".equals(type);p.setPassportTypeEn(firstNonBlank(string(e,"passportTypeEn"),t?"Valid ordinary passport of an eligible country/region":m?"Passport covered by the applicable bilateral agreement":"Valid ordinary passport"));p.setPassportTypeZh(firstNonBlank(string(e,"passportTypeZh"),t?"符合过境免签条件国家/地区的有效普通护照":m?"适用双边互免签证协定的护照":"有效普通护照"));p.setPassportValidityEn(firstNonBlank(string(e,"passportValidityEn"),t?"Passport and transit-document requirements must meet the current transit policy.":"Passport requirements follow the applicable entry policy."));p.setPassportValidityZh(firstNonBlank(string(e,"passportValidityZh"),t?"护照及过境旅行证件要求须符合当前过境政策。":"护照要求以适用入境政策为准。"));p.setEntryCountEn(firstNonBlank(string(e,"entryCountEn"),t?"Transit conditions and permitted stay follow the current 240-hour policy.":m?"Entry frequency and stay limits follow the applicable bilateral agreement.":"Entry conditions and stay limits follow the current unilateral policy."));p.setEntryCountZh(firstNonBlank(string(e,"entryCountZh"),t?"过境条件及停留期限以当前240小时过境免签政策为准。":m?"入境次数及停留期限以适用双边协定为准。":"入境条件及停留期限以当前单方面免签政策为准。"));p.setOnwardTicketEn(firstNonBlank(string(e,"onwardTicketEn"),t?"A confirmed onward itinerary to a third country or region is required.":"Check the current return or onward travel requirements for your itinerary."));p.setOnwardTicketZh(firstNonBlank(string(e,"onwardTicketZh"),t?"需要前往第三国或地区的已确认联程行程。":"请根据实际行程核对返程或后续行程材料要求。"));p.setAccommodationEn(firstNonBlank(string(e,"accommodationEn"),"Keep accommodation information available if requested at entry inspection."));p.setAccommodationZh(firstNonBlank(string(e,"accommodationZh"),"如入境查验需要，请准备住宿信息。"));p.setFinancialProofEn(firstNonBlank(string(e,"financialProofEn"),"Prepare trip-related supporting documents if requested."));p.setFinancialProofZh(firstNonBlank(string(e,"financialProofZh"),"如被要求，请准备与行程相关的证明材料。"));p.setExtensionRuleEn(firstNonBlank(string(e,"extensionRuleEn"),"Do not assume a visa-free stay can be extended; contact the local immigration authority before expiry."));p.setExtensionRuleZh(firstNonBlank(string(e,"extensionRuleZh"),"不要默认免签停留可以延期；如需延长，应在期限届满前咨询当地出入境管理部门。"));populateFaqs(p,d,type,e);return p;}
    private void populateFaqs(CountryPolicy p,CountryDetail d,String type,Map<String,Object>e){List<CountryPolicy.PolicyFaq>en=toFaqs(e.get("customFaqsEn")),zh=toFaqs(e.get("customFaqsZh"));String stay=isBlank(d.getStayDays())?"the period stated by the policy":d.getStayDays()+" days",stayZh=isBlank(d.getStayDays())?"政策规定期限":d.getStayDays()+"天";if("transit".equals(type)){addIfMissing(en,"How long can "+d.getName()+" citizens stay under this transit route?","The current policy record allows up to "+stay+", subject to the qualifying transit itinerary and entry record.");addIfMissing(zh,d.getNameZh()+"公民过境免签可以停留多久？","当前政策记录允许最长停留"+stayZh+"，具体以符合条件的过境行程和入境记录为准。");}else if("mutual".equals(type)){addIfMissing(en,"Do "+d.getName()+" citizens need a visa under this agreement?","A visa may be waived when the passport and purpose meet the applicable bilateral agreement.");addIfMissing(zh,d.getNameZh()+"公民按照互免协定去中国需要签证吗？","满足适用双边互免签证协定条件时，可以免办签证入境。");}else{addIfMissing(en,"Can "+d.getName()+" citizens enter China without a visa?","They may qualify when the ordinary passport, purpose and stay conditions of the current policy are met.");addIfMissing(zh,d.getNameZh()+"公民可以免签进入中国吗？","满足当前普通护照、出行目的和停留条件时，可能适用中国免签安排。");}p.setFaqsEn(en);p.setFaqsZh(zh);}
    private void addIfMissing(List<CountryPolicy.PolicyFaq>l,String q,String a){for(CountryPolicy.PolicyFaq f:l)if(q.equalsIgnoreCase(f.getQ()))return;l.add(new CountryPolicy.PolicyFaq(q,a));}
    private List<CountryPolicy.PolicyFaq>toFaqs(Object v){List<CountryPolicy.PolicyFaq>r=new ArrayList<>();if(!(v instanceof List))return r;for(Object x:(List<?>)v){if(!(x instanceof Map))continue;Map<?,?>m=(Map<?,?>)x;String q=string(m.get("q")),a=string(m.get("a"));if(!isBlank(q)&&!isBlank(a))r.add(new CountryPolicy.PolicyFaq(q,a));}return r;}
    private CountryDetail syntheticUnilateral(String key){if(!CURRENT_UNILATERAL_30.contains(key))return null;CountryDetail d=new CountryDetail();d.setCode(key);if("kyrgyzstan".equals(key)){d.setName("Kyrgyzstan");d.setNameZh("吉尔吉斯斯坦");d.setContinent("Asia");d.setContinentZh("亚洲");}else{d.setName("Vietnam");d.setNameZh("越南");d.setContinent("Asia");d.setContinentZh("亚洲");}d.setPolicyType("unilateral");d.setPolicyTypeZh("单方面免签（中国给予）");d.setStayDays("30");d.setValidFrom("2026-08-20");d.setPurpose("Business, tourism, family visit, exchange, transit");d.setPurposeZh("经商、旅游观光、探亲访友、交流访问、过境");d.setRule("Stay no more than 30 days. Period starts from 00:00 next day.");d.setRuleZh("停留不超过30日，停留时间自入境次日零时起算");d.setPorts("All open ports of China");d.setPortsZh("全国所有对外开放口岸");d.setSeoTitle(d.getName()+" to China Visa-Free Policy 2026 | 30 Days Unilateral");d.setSeoTitleZh(d.getNameZh()+"来华免签政策2026 | 单方面30天免签");return d;}
    private List<String>detectAvailableTypes(String code){String k=resolver.policyKey(code);List<String>r=new ArrayList<>();if(unilateralMap.containsKey(k)||CURRENT_UNILATERAL_30.contains(k))r.add("unilateral");if(mutualMap.containsKey(k))r.add("mutual");if(transitMap.containsKey(k))r.add("transit");return r;}
    private CountryDetail getCountryDetail(String code,String type){String k=resolver.policyKey(code);if("unilateral".equals(type)){CountryDetail d=unilateralMap.get(k);return d!=null?d:syntheticUnilateral(k);}if("mutual".equals(type))return mutualMap.get(k);if("transit".equals(type))return transitMap.get(k);return null;}
    private CountryDetail getAnyCountryDetail(String code){String k=resolver.policyKey(code);CountryDetail d=unilateralMap.get(k);if(d!=null)return d;d=mutualMap.get(k);if(d!=null)return d;d=transitMap.get(k);return d!=null?d:syntheticUnilateral(k);}
    private String routeCode(String code){return resolver.routeCode(resolver.policyKey(code));}
    private Map<String,Object>getCountryExtraRoot(String code){Map<String,Object>m=countryExtraMap.get(code);return m!=null?m:countryExtraMap.get(routeCode(code));}
    private Object getCountryExtraItem(String code,String type){Map<String,Object>m=getCountryExtraRoot(code);return m==null?null:m.get(type);}
    private List<CountryDetail>buildAvailablePolicies(String code,List<String>types){List<CountryDetail>r=new ArrayList<>();for(String t:types){CountryDetail d=getCountryDetail(code,t);if(d!=null)r.add(d);}return r;}
    private Map<String,CountryDetail>buildPolicyDetails(String code,List<String>types){Map<String,CountryDetail>r=new LinkedHashMap<>();for(String t:types){CountryDetail d=getCountryDetail(code,t);if(d!=null)r.put(t,d);}return r;}
    private Map<String,String>buildCountryNames(){Map<String,String>r=new LinkedHashMap<>();addNames(r,unilateralMap);addNames(r,mutualMap);addNames(r,transitMap);return r;}
    private void addNames(Map<String,String>r,Map<String,CountryDetail>m){m.forEach((k,v)->r.putIfAbsent(routeCode(k),v.getName()));}
    private List<String>buildRelatedCountryCodes(Map<String,Object>e){List<String>r=new ArrayList<>();if(e==null)return r;Object v=e.get("relatedCountryCodes");if(!(v instanceof List))return r;for(Object x:(List<?>)v){String c=string(x);if(!isBlank(c)&&getAnyCountryDetail(c)!=null&&!r.contains(c))r.add(c);}return r;}
    private Map<String,CountryDetail>loadCountryMap(ObjectMapper m,String f){try{return m.readValue(new ClassPathResource(f).getInputStream(),new TypeReference<Map<String,CountryDetail>>(){});}catch(Exception e){throw new IllegalStateException("Failed to load "+f,e);}}
    private Map<String,Map<String,Object>>loadExtraMap(ObjectMapper m){try{return m.readValue(new ClassPathResource("country-extra.json").getInputStream(),new TypeReference<Map<String,Map<String,Object>>>(){});}catch(Exception e){throw new IllegalStateException("Failed to load country-extra.json",e);}}
    private Map<String,Object>asMap(Object v){if(v instanceof Map){Map<String,Object>r=new LinkedHashMap<>();((Map<?,?>)v).forEach((k,x)->r.put(String.valueOf(k),x));return r;}return new LinkedHashMap<>();}
    private String string(Map<String,Object>m,String k){return m==null?"":string(m.get(k));}private String string(Object v){return v==null?"":String.valueOf(v).trim();}private String firstNonBlank(String v,String f){return isBlank(v)?f:v;}private boolean isBlank(String v){return v==null||v.trim().isEmpty();}private int number(Object v,int f){if(v instanceof Number)return((Number)v).intValue();try{return Integer.parseInt(string(v));}catch(Exception e){return f;}}
}