spring:
  # 数据源配置（支持H2内存库/MySQL）
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  url: jdbc:mysql://192.168.10.5:3306/laonianai?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://192.168.10.5:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  # Thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  # 静态资源配置
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/

# MyBatis配置
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.laonianai.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

# 自定义配置
laonianai:
  admin:
    username: admin
    password: 123456